### ISSUE TITLE
Working with Reactive Forms

### ISSUE THREAD

**Issue by comfortme** [hansmaad/ng-units#66]
Hi,
When I tried to use ngQuantity with reactive forms, I get the below error.
Is there a way to work with reactive forms or am I doing it wrong?

`Error: More than one custom value accessor matches form control with path: 'frame -> '`

```
<form [formGroup]="form">
<div formGroupName="frame">
<input formControlName="width" ngQuantity="Length"/>
</div>
</form>
```

**Comment by comfortme** [comment]
figured this error is due to I’m using ionic. 
it works with native input but not with ion-input which is a wrapper for native input from ionic framework. 
so I guess I can’t use this library if I’m using ionic input.

**Comment by hansmaad** [comment]
The QuantityDirective is a ControlValueAccessor and there can only be one ControlValueAccessor  directive on the same element at a time. If you're using a directive from some library on the input element that is also a ControlValueAccessor, it won't work.
